### ISSUE TITLE
"AssertionError: the constraints must have the same normal direction"  after  passed "samedir" check.

### ISSUE THREAD

**Issue by Wei-TianHao** [JuliaReach/LazySets.jl#2386]
```julia
HPolytope{Float64,Array{Float64,1}}(HalfSpace{Float64,Array{Float64,1}}[HalfSpace{Float64,Array{Float64,1}}([1.0, 0.0], 1.0), HalfSpace{Float64,Array{Float64,1}}([0.0, 1.0], 1.0), HalfSpace{Float64,Array{Float64,1}}([-1.0, 0.0], 1.0), HalfSpace{Float64,Array{Float64,1}}([0.0, -1.0], 1.0), HalfSpace{Float64,Array{Float64,1}}([0.17178027783046604, -0.342877222169534], -0.3988040749330524), HalfSpace{Float64,Array{Float64,1}}([0.17228094170254737, -0.3438765582974526], -0.5161575)])

AssertionError: the constraints must have the same normal direction

Stacktrace:
 [1] macro expansion at /home/wth/.julia/packages/LazySets/FwmiZ/src/Assertions/Assertions.jl:23 [inlined]
 [2] is_tighter_same_dir_2D(::HalfSpace{Float64,Array{Float64,1}}, ::HalfSpace{Float64,Array{Float64,1}}; strict::Bool) at /home/wth/.julia/packages/LazySets/FwmiZ/src/Sets/HalfSpace.jl:460
 [3] isredundant(::HalfSpace{Float64,Array{Float64,1}}, ::HalfSpace{Float64,Array{Float64,1}}, ::HalfSpace{Float64,Array{Float64,1}}) at /home/wth/.julia/packages/LazySets/FwmiZ/src/Interfaces/AbstractHPolygon.jl:348
 [4] addconstraint!(::Array{HalfSpace{Float64,Array{Float64,1}},1}, ::HalfSpace{Float64,Array{Float64,1}}; linear_search::Bool, prune::Bool) at /home/wth/.julia/packages/LazySets/FwmiZ/src/Interfaces/AbstractHPolygon.jl:521
 [5] #addconstraint!#72 at /home/wth/.julia/packages/LazySets/FwmiZ/src/Interfaces/AbstractHPolygon.jl:434 [inlined]
 [6] convert(::Type{HPolygon}, ::HPolytope{Float64,Array{Float64,1}}; prune::Bool) at /home/wth/.julia/packages/LazySets/FwmiZ/src/convert.jl:239
 [7] vertices_list(::HPolytope{Float64,Array{Float64,1}}; backend::Nothing, prune::Bool) at /home/wth/.julia/packages/LazySets/FwmiZ/src/Sets/HPolytope.jl:218
 [8] vertices_list at /home/wth/.julia/packages/LazySets/FwmiZ/src/Sets/HPolytope.jl:213 [inlined]
 [9] area(::HPolytope{Float64,Array{Float64,1}}) at /home/wth/.julia/packages/LazySets/FwmiZ/src/Interfaces/LazySet.jl:944
 [10] ordinal_split!(::IntervalNet, ::Problem{HPolytope{Float64,Array{Float64,1}},HPolytope{Float64,Array{Float64,1}}}, ::NeuralVerification.Tree{Tuple{HPolytope{Float64,Array{Float64,1}},Array{Any,1}}}, ::Int64, ::Int64, ::Array{Tuple{Int64,Int64},1}) at /home/wth/dev/NeuralVerification.jl/src/runtime/trainingVerification.jl:59
 [11] init_split at /home/wth/dev/NeuralVerification.jl/src/runtime/trainingVerification.jl:91 [inlined]
 [12] solve(::TrainingProblem{HPolytope{Float64,Array{Float64,1}},HPolytope{Float64,Array{Float64,1}}}, ::Int64, ::Bool, ::Bool, ::Float64, ::Bool) at /home/wth/dev/NeuralVerification.jl/src/runtime/trainingVerification.jl:320
 [13] macro expansion at ./timing.jl:310 [inlined]
 [14] test2D(::String, ::Int64, ::Bool, ::Bool, ::Float64, ::Bool) at ./In[3]:42
 [15] test2D(::String, ::Int64, ::Bool, ::Bool, ::Float64) at ./In[3]:28
 [16] top-level scope at In[20]:1
 [17] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091
```

**Comment by schillic** [comment]
This is the whole script to reproduce:

```julia
julia> P = HPolytope([
 HalfSpace([1.0, 0.0], 1.0),
 HalfSpace([0.0, 1.0], 1.0),
 HalfSpace([-1.0, 0.0], 1.0),
 HalfSpace([0.0, -1.0], 1.0),
 HalfSpace([0.17178027783046604, -0.342877222169534], -0.3988040749330524),
 HalfSpace([0.17228094170254737, -0.3438765582974526], -0.5161575)
]);

julia> vertices_list(P)
```

**Comment by mforets** [comment]
@Wei-TianHao  thanks for reporting. If we split `P` into its first four constraints (box), and call `c5` and `c6` the remaining constraints, then `c5` and `c6` are redundant. Moreover, the set `P` is actually a singleton (the top-left corner of the box).

![Screenshot from 2020-10-22 14-15-35](https://user-images.githubusercontent.com/12424594/96907061-1caea680-1471-11eb-93b5-45ccf4d96475.png)

**Comment by schillic** [comment]
I found the problem. It is an approximation issue. I'll send a fix soon.

**Comment by mforets** [comment]
the issue has been solved on `LazySets#master`, and will be available in the next patch release v1.37.12 (https://github.com/JuliaRegistries/General/pull/23523).

**Comment by Wei-TianHao** [comment]
I still get this problem after update. Can you check it again? Thanks!

HPolytope{Float64,Array{Float64,1}}(HalfSpace{Float64,Array{Float64,1}}[HalfSpace{Float64,Array{Float64,1}}([1.0, 0.0], 1.0), HalfSpace{Float64,Array{Float64,1}}([0.0, 1.0], 1.0), HalfSpace{Float64,Array{Float64,1}}([-1.0, 0.0], 1.0), HalfSpace{Float64,Array{Float64,1}}([0.0, -1.0], 1.0), HalfSpace{Float64,Array{Float64,1}}([0.5441407272182882, -0.4970972727817118], -0.43429992242166565), HalfSpace{Float64,Array{Float64,1}}([0.5441929862337312, -0.4971450137662688], -1.0413379999999999)])
AssertionError: the constraints must have the same normal direction

**Comment by schillic** [comment]
For me this works:
```julia
julia> HPolytope([HalfSpace([1.0, 0.0], 1.0), HalfSpace([0.0, 1.0], 1.0),
 HalfSpace([-1.0, 0.0], 1.0), HalfSpace([0.0, -1.0], 1.0),
 HalfSpace([0.5441407272182882, -0.4970972727817118], -0.43429992242166565),
 HalfSpace([0.5441929862337312, -0.4971450137662688], -1.0413379999999999)])
```
Which version of `LazySets` do you use (`pkg> status`)?

Also, what you posted is the print output of the set. How did you print it if there is an error? To me it seems that it works and the error is somewhere else. Can you add the exact *input* command to reproduce (or a link to a notebook), please?

**Comment by Wei-TianHao** [comment]
Sorry I paste the wrong info. I'm using v1.37.12.

Here is the code to reproduce the error.
``` julia
P = HPolygon([
 HalfSpace([1.0, 0.0], 1.0),
 HalfSpace([0.0, 1.0], 1.0),
 HalfSpace([-1.0, 0.0], 1.0),
 HalfSpace([0.0, -1.0], 1.0),
 HalfSpace([-0.36055286066599984, -0.42545113933400025], -0.18569492232099608),
 HalfSpace([0.36059873229778105, 0.4255052677022189], 0.786104),
 HalfSpace([0.29309206951160244, 0.2422611611544917], 0.2784325170418686),
 HalfSpace([0.29321219191989917, 0.24236045075370585], 0.047383642673605064),
])
```

**Comment by mforets** [comment]
```julia
P = HPolygon([
 HalfSpace([1.0, 0.0], 1.0),
 HalfSpace([0.0, 1.0], 1.0),
 HalfSpace([-1.0, 0.0], 1.0),
 HalfSpace([0.0, -1.0], 1.0),
 HalfSpace([-0.36055286066599984, -0.42545113933400025], -0.18569492232099608),
 HalfSpace([0.36059873229778105, 0.4255052677022189], 0.786104),
 HalfSpace([0.29309206951160244, 0.2422611611544917], 0.2784325170418686),
 HalfSpace([0.29321219191989917, 0.24236045075370585], 0.047383642673605064),
])
```
works for me in lazysets#master. @Wei-TianHao please re-open if it's not the case.
